const xmltvTags = [
  "actor",
  "adapter",
  "aspect",
  "audio",
  "category",
  "channel",
  "colour",
  "commentator",
  "composer",
  "country",
  "credits",
  "date",
  "desc",
  "director",
  "display-name",
  "editor",
  "episode-num",
  "guest",
  "icon",
  "image",
  "keyword",
  "language",
  "last-chance",
  "length",
  "new",
  "orig-language",
  "premiere",
  "present",
  "presenter",
  "previously-shown",
  "producer",
  "programme",
  "quality",
  "rating",
  "review",
  "star-rating",
  "stereo",
  "sub-title",
  "subtitles",
  "title",
  "tv",
  "url",
  "value",
  "video",
  "writer",
] as const;

const xmltvAttributes = [
  "channel",
  "clumpidx",
  "date",
  "generator-info-name",
  "generator-info-url",
  "guest",
  "height",
  "id",
  "lang",
  "orient",
  "pdc-start",
  "reviewer",
  "role",
  "showview",
  "size",
  "source-data-url",
  "source-info-name",
  "source-info-url",
  "source",
  "src",
  "start",
  "stop",
  "system",
  "type",
  "units",
  "videoplus",
  "vps-start",
  "width",
] as const;

type XmltvTags = (typeof xmltvTags)[number];
type XmltvAttributes = (typeof xmltvAttributes)[number];

export { xmltvTags, xmltvAttributes, XmltvTags, XmltvAttributes };
